### ISSUE TITLE
Create a box that will contain our game modes / join diferent rooms

### ISSUE THREAD

**Issue by Boghydy** [BRA-Team/kick-off-picks#14]
### Task

- [ ] scrooll some images on hover
- [ ] button for create room
- [ ] button for join room

![Image](https://github.com/BRA-Team/kick-off-picks/assets/126898116/e84b8c8e-05b7-45e3-ae81-d55776462359)
